### PR TITLE
Updates bin files to Microsoft/TypeScript@master LKG.

### PR DESCRIPTION
**Pull request by MicahZoltu**
https://github.com/Microsoft/TypeScript/commit/965f994acefd238dc0c473e739d7916c47bf41b4

I'm not sure if this is the right process, or if there is a desire to just migrate over 1.5.3 release bits rather than pulling in the latest master LKG bits.  Either way, I figured a PR was a reasonable place to start the conversation.

### CODE REVIEW

**Comment by mhegazy** [comment]
I do not really want to keep this up for long. it was just to unblock a few folks, but somehow became an "official" release :)

release-1.5.3 is out, so this should be more up-to-date, and https://github.com/Microsoft/TypeScript/pull/3875 will allow us to publish prereleases nightly, hopefully gets merged today, and publish tonight.

so unless i missed something else, i would close this PR.

**Comment by MicahZoltu** [comment]
The big value of this repo is the fact that it only has the bin files (~1.5MB) and you can point a GitHub friendly package manager at it (e.g., JSPM).  If you point JSPM (or some other package manager) at github:Microsoft/TypeScript, you have to pull down ~20MB of files.

Do you happen to know if the nightly releases will include _just_ the compiler (rather than the full source base)?  JSPM also supports NPM, so if NPM has the latest bin-only release that will be fine for my use case at least.

**Comment by mhegazy** [comment]
it should only have latest bin, and it will be published to npm, so no need to clone the whole repo.

**Comment by MicahZoltu** [comment]
In that case, I'm content to close this and I'll work with JSPM to migrate to NPM for getting the latest TypeScript bits.

**Comment by antonmoiseev** [comment]
@Zoltu thanks for asking this question, it helped to figure out the way to use latest stable TS version with JSPM.

**Comment by mhegazy** [comment]
For future references, please use `typescript@next` instead of this fork. see [typescript nightlies](http://blogs.msdn.com/b/typescript/archive/2015/07/27/introducing-typescript-nightlies.aspx) for more information.

**Pull request closed without merging**
